function [fitresult, gof] = createFit(up_t, ex)
%CREATEFIT(UP_T,EX)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : up_t
%      Y Output: ex
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 26-Jun-2022 14:46:23


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( up_t, ex );

% Set up fittype and options.
ft = fittype( 'a*exp(-exp(b-c*(t-d)))+e', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -20 0];
opts.StartPoint = [0.141886338627215 0.421761282626275 0.915735525189067 0.792207329559554 0.959492426392903];
opts.Upper = [Inf Inf Inf 20 0.009];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'ex vs. up_t', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'up_t', 'Interpreter', 'none' );
ylabel( 'ex', 'Interpreter', 'none' );
grid on


