function [fitresult, gof] = ScanlanFit(ex, epsx)
%CREATEFIT(EX,EPSX)
%  Create a fit.
%
%  Data for 'ScanlanModel' fit:
%      X Input : ex
%      Y Output: epsx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Jun-2022 22:45:51


%% Fit: 'ScanlanModel'.
[xData, yData] = prepareCurveData( ex, epsx );

% Set up fittype and options.
ft = fittype( 'a+b*x^2', 'independent', 'x', 'dependent', 'y' );
% a=rho*U*D*Y1/(-2*m*w0);b=-rho*U*D*Y1*epsilon/4/(-2*m*w0);
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0467146341418908 0.959189869693014];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ScanlanModel' );
h = plot( fitresult, xData, yData );
legend( h, 'epsx vs. ex', 'ScanlanModel', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'ex', 'Interpreter', 'none' );
ylabel( 'epsx', 'Interpreter', 'none' );
grid on


